"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-ml' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex_context",
    "scitex_dev",
    "scitex_io",
    "scitex_logging",
    "scitex_plt",
    "scitex_plt.colors",
    "scitex_repro",
    "scitex_seizure_metrics",
    "scitex_str",
    "scitex_types",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_succeeds_for_declared_dependency(module_name):
    # Arrange
    pytest.importorskip(module_name)
    # Act
    module = __import__(module_name)
    # Assert
    assert module is not None
