"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-ml' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
# NOTE: entries beginning with `scitex_ml.` are self-imports of this very
# package (the standalone `scitex-ml` distribution → `scitex_ml` import).
# They are listed here because the upstream PS-140 auditor in
# `scitex-dev v0.12.3` determines the "own import name" from the repository
# directory basename (`<dir>.replace("-", "_")`). When this repo is checked
# out under a non-canonical directory (e.g. a git worktree such as
# `scitex-ml-fix-skip/`), the derived own-name becomes
# `scitex_ml_fix_skip`, and the auditor then flags every legitimate
# intra-package `scitex_ml.<sub>` import as a missing cross-package entry.
# Listing them here keeps the gate exhaustive for both the canonical
# checkout AND any worktree; the test simply does
# `pytest.importorskip(module_name)` so resolving each name as its own
# package is harmless.
# Filed upstream context: scitex-dev PS-140
# (`_check_umbrella_dep_and_integration._own_import_name`) should use the
# distribution name from the ECOSYSTEM registry, not the repo basename.
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex_context",
    "scitex_dev",
    "scitex_io",
    "scitex_logging",
    "scitex_ml.classification",
    "scitex_ml.feature_selection",
    "scitex_ml.metrics",
    "scitex_ml.plt",
    "scitex_ml.plt._plot_pre_rec_curve",
    "scitex_ml.plt._plot_roc_curve",
    "scitex_ml.plt._stx_conf_mat",
    "scitex_plt",
    "scitex_plt.colors",
    "scitex_repro",
    "scitex_seizure_metrics",
    "scitex_str",
    "scitex_types",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_succeeds_for_declared_dependency(module_name):
    # Arrange
    pytest.importorskip(module_name)
    # Act
    module = __import__(module_name)
    # Assert
    assert module is not None
