"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-ml' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
# NOTE: scitex_ml.* self-imports are deliberately OMITTED. The upstream
# PS-140 auditor in scitex-dev v0.12.3 disagrees with itself on whether
# self-imports belong in the cross-package gate:
#   - In a non-canonical checkout dir (e.g. worktree `scitex-ml-fix-skip/`)
#     `_own_import_name` derives `scitex_ml_fix_skip` and flags every
#     `scitex_ml.<sub>` reference as "missing from gate"
#   - In the canonical CI checkout `scitex-ml/` it derives `scitex_ml` and
#     flags those same entries as "stale in gate"
# CI is the source of truth → keep self-imports OUT of the gate.
# Upstream fix needed: `_own_import_name` should use the distribution name
# from the ECOSYSTEM registry, not the repo directory basename.
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex_context",
    "scitex_dev",
    "scitex_io",
    "scitex_logging",
    "scitex_plt",
    "scitex_plt.colors",
    "scitex_repro",
    "scitex_seizure_metrics",
    "scitex_str",
    "scitex_types",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_succeeds_for_declared_dependency(module_name):
    # Arrange
    pytest.importorskip(module_name)
    # Act
    module = __import__(module_name)
    # Assert
    assert module is not None
