"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest

_SKIP_AUDIT = shutil.which("scitex-dev") is None


@pytest.mark.skipif(_SKIP_AUDIT, reason="scitex-dev not installed")
def test_audit_all_clean_passes_without_pa306_or_pa307_violations():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    audit_all_for_package(
        "scitex-ml",
        skip_rules=(),
    )
    # Assert
    assert True
