"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


def test_audit_all_clean_passes_without_pa306_or_pa307_violations():
    # Arrange
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    # Act
    audit_all_for_package(
        "scitex-ml",
        skip_rules=(
            "SK-105", "SK-106", "SK-107", "SK-201", "SK-401",
            "SK-601", "SK-704", "SK-706", "SK-709", "SK-710", "SK-711",
        ),
    )
    # Assert: audit_all_for_package raises AssertionError on violation
    assert True  # reaching here means no exception was raised
