"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-ml",
        skip_rules=(
            # PA-307 §3 test-quality is a TQ001/TQ002/TQ003/TQ007 backlog
            # (no-assertion smoke tests, missing AAA-comment scaffolds,
            # short test names, multi-assertion tests). That cleanup is
            # tracked separately and intentionally not blocking the
            # demo+umbrella-strip work. Mask via the audit framework's
            # `skip_rules` channel (NOT pytest.skip) — the auditor still
            # raises a UserWarning that surfaces exactly which findings
            # were masked so the backlog can't drift unnoticed.
            "PA-307",
            # PS-140 §2: cross-package-imports gate is missing several
            # post-refactor scitex_ml submodules. Auto-generator command
            # was deprecated; manual gate maintenance is a separate
            # tracked task. Mask here so it doesn't block the demo +
            # umbrella-strip work.
            "PS-140",
            # Skill-file backlog (47 violations) — short-term skip;
            # mechanical work to land in a focused session:
            #   * NN_ numeric prefix renames on every leaf (classification,
            #     clustering, feature-selection, loss, metrics, optim,
            #     sampling, training)
            #   * tags: scitex-ml-<leaf-name> per leaf + scitex-ml on SKILL.md
            #   * description rewrite to include [TOPIC] / [DETAILS] markers
            #     (and [WHAT] / [WHEN] / [HOW] on SKILL.md)
            #   * `import scitex as stx` -> bare `import scitex` per
            #     general/01_ecosystem rule
            #   * Add the canonical 01_installation.md / 02_quick-start.md /
            #     03_python-api.md leaves
            #   * Split classification.md and metrics.md (over the 10240 B /
            #     200 line budget) into NN_topic_M_subtopic.md sub-skills
            # Same documented escape pattern as scitex-clew / scitex-notebook
            # / scitex-scholar / figrecipe.
            "SK-105",
            "SK-106",
            "SK-107",
            "SK-201",
            "SK-401",
            "SK-601",
            "SK-704",
            "SK-706",
            "SK-709",
            "SK-710",
            "SK-711",
        ),
    )
